/**
 * Pull the latin subset of each face into public/fonts/ and emit a local @font-face
 * stylesheet. Self-hosted on purpose: no CDN means nothing silently falls back to a
 * system font on race day when the venue wifi is bad.
 *
 *   bun run tools/fetch-fonts.ts
 */
import { mkdir, writeFile } from "node:fs/promises";

const FAMILIES = [
  "Big+Shoulders+Display:wght@600;700;800",
  "Archivo:wght@400;500;600;700",
  "IBM+Plex+Mono:wght@400;500",
];

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Kept inside src/ rather than public/ so Vite fingerprints and bundles them,
// which gives cache-busting for free and avoids shipping two copies.
const OUT_DIR = "src/client/styles/fonts";
const CSS_OUT = "src/client/styles/fonts.css";

type Face = {
  block: string;
  url: string;
};

/** Split the CSS2 response into blocks, keeping only the ones labelled `/* latin *\/`. */
function latinFaces(css: string): Face[] {
  const faces: Face[] = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m: RegExpExecArray | null;

  while ((m = re.exec(css)) !== null) {
    const [, subset, block] = m;
    if (subset !== "latin") {
      continue;
    }
    const url = block.match(/url\((https:\/\/[^)]+)\)/)?.[1];
    if (!url) {
      continue;
    }
    faces.push({ block, url });
  }

  return faces;
}

function fileNameFor(block: string, index: number): string {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? `face-${index}`;
  const weight = block.match(/font-weight:\s*([\d\s]+);/)?.[1]?.trim().replace(/\s+/g, "-") ?? "400";
  const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `${slug}-${weight}.woff2`;
}

await mkdir(OUT_DIR, { recursive: true });

const chunks: string[] = [
  "/* Generated by tools/fetch-fonts.ts — do not edit by hand. */",
  "",
];
let count = 0;

for (const family of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${family}&display=swap`, {
    headers: { "User-Agent": UA },
  });

  if (!res.ok) {
    throw new Error(`${family}: HTTP ${res.status}`);
  }

  const faces = latinFaces(await res.text());
  if (faces.length === 0) {
    throw new Error(`${family}: no latin subset found`);
  }

  for (const face of faces) {
    const name = fileNameFor(face.block, count);
    const bin = await fetch(face.url);

    if (!bin.ok) {
      throw new Error(`${name}: HTTP ${bin.status}`);
    }

    await writeFile(`${OUT_DIR}/${name}`, Buffer.from(await bin.arrayBuffer()));

    // Keep every descriptor Google emitted (weight ranges, stretch, unicode-range);
    // only the source URL becomes local.
    chunks.push(face.block.replace(/src:\s*url\([^)]+\)/, `src: url(./fonts/${name})`));
    chunks.push("");
    count += 1;
    console.log(`  ${name}`);
  }
}

await writeFile(CSS_OUT, chunks.join("\n"));
console.log(`\n${count} faces → ${OUT_DIR}, stylesheet → ${CSS_OUT}`);
